[manager]
ratio          = [ 1, 3, 4 ]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
show_hidden    = true
show_symlink   = true

[opener]
edit = [ { run = '${EDITOR:-nvim} "$@"', block = true, desc = "edit" }, ]
open = [ { run = 'xdg-open "$@"', desc = "system open" }, ]
imv = [ { run = 'imv "$@"', orphan = true, desc = "imv" }, ]
mpv-image = [ { run = 'mpv "$@"', orphan = true, desc = "mpv (Image)" }, ]
mpv = [ { run = 'mpv "$@"', orphan = true, desc = "mpv" }, ]
folder = [ { run = '${EDITOR:-nvim} "$1"', block = true, desc = "neovim" }, ]

[open]
rules = [
    { mime = "folder/local", use = [ "folder", "open", "folder" ] },
	{ mime = "text/*", use = [ "edit", "open" ] },
	{ mime = "image/*", use = [ "imv", "open" ] },
    { mime = "{audio,video}/*", use = [ "mpv", "open" ] },
    { mime = "application/*", use = [ "edit", "open"] },
    { mime = "inode/empty", use = [ "edit", "open" ] },
]

[tasks]
micro_workers    = 10
macro_workers    = 25
bizarre_retry    = 5
