[manager]
ratio          = [ 1, 3, 4 ]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
show_hidden    = true
show_symlink   = true

[opener]
edit = [
	{ run = '${EDITOR:-nvim} "$@"', block = true, desc = "Edit" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
imv = [
    { run = 'imv "$@"', detach = true, desc = "Open with imv" },
]
mpv = [
    { run = 'mpv "$@"', detach = true, desc = "Open with mpv" },
]
font-preview = [
	{ run = 'gnome-font-viewer "$@"', desc = "Open with GNOME Font Viewer", block = false }
]

[open]
rules = [
	{ name = "*/", use = [ "edit", "open" ] },
	{ mime = "text/*", use = [ "edit", "open" ] },
	{ mime = "image/*", use = [ "imv", "open" ] },
    { mime = "audio/*", use = [ "mpv", "open" ] },
	{ mime = "video/*", use = [ "mpv", "open" ] },
    { mime = "font/*", use = "font-preview" },
    { mime = "application/*", use = [ "edit", "open"] },
    { mime = "inode/empty", use = [ "edit", "open" ] },
    { name = "*", use = [ "edit", "open" ] },
]

[tasks]
micro_workers    = 10
macro_workers    = 25
bizarre_retry    = 5
