[manager]
ratio          = [ 1, 3, 4 ]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
show_hidden    = true
show_symlink   = true

[opener]
edit = [ { run = '${EDITOR:-nvim} "$@"', block = true, desc = "Edit" }, ]
open = [ { run = 'xdg-open "$@"', desc = "Open" }, ]
imv = [ { run = 'imv "$@"', orphan = true, desc = "Open with imv" }, ]
mpv = [ { run = 'mpv "$@"', orphan = true, desc = "Open with mpv" }, ]
font-preview = [ { run = '~/.local/bin/fv -f "$@"', desc = "Open with Scripts Font Viewer", block = true }, ]

[open]
rules = [
	{ mime = "text/*", use = [ "edit", "open" ] },
	{ mime = "image/*", use = [ "imv", "open" ] },
    { mime = "{audio,video}/*", use = [ "mpv", "open" ] },
    { mime = "font/*", use = "font-preview" },
    { mime = "application/*", use = [ "edit", "open"] },
    { mime = "inode/empty", use = [ "edit", "open" ] },
]

[tasks]
micro_workers    = 10
macro_workers    = 25
bizarre_retry    = 5
