# matugen 配色文件


$background = rgba(141318ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(312f36ff)

$inverse_primary = rgba(615690ff)

$inverse_surface = rgba(e6e1e9ff)

$on_background = rgba(e6e1e9ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(32285eff)

$on_primary_container = rgba(e6deffff)

$on_primary_fixed = rgba(1d1148ff)

$on_primary_fixed_variant = rgba(493e76ff)

$on_secondary = rgba(322e41ff)

$on_secondary_container = rgba(e6dff9ff)

$on_secondary_fixed = rgba(1d192bff)

$on_secondary_fixed_variant = rgba(484458ff)

$on_surface = rgba(e6e1e9ff)

$on_surface_variant = rgba(c9c4d0ff)

$on_tertiary = rgba(492534ff)

$on_tertiary_container = rgba(ffd9e5ff)

$on_tertiary_fixed = rgba(30111fff)

$on_tertiary_fixed_variant = rgba(623b4bff)

$outline = rgba(938f99ff)

$outline_variant = rgba(48454eff)

$primary = rgba(cbbeffff)

$primary_container = rgba(493e76ff)

$primary_fixed = rgba(e6deffff)

$primary_fixed_dim = rgba(cbbeffff)

$scrim = rgba(000000ff)

$secondary = rgba(cac3dcff)

$secondary_container = rgba(484458ff)

$secondary_fixed = rgba(e6dff9ff)

$secondary_fixed_dim = rgba(cac3dcff)

$shadow = rgba(000000ff)

$source_color = rgba(766ba4ff)

$surface = rgba(141318ff)

$surface_bright = rgba(3a383eff)

$surface_container = rgba(201f24ff)

$surface_container_high = rgba(2b292fff)

$surface_container_highest = rgba(36343aff)

$surface_container_low = rgba(1c1b20ff)

$surface_container_lowest = rgba(0f0d13ff)

$surface_dim = rgba(141318ff)

$surface_tint = rgba(cbbeffff)

$surface_variant = rgba(48454eff)

$tertiary = rgba(eeb8cbff)

$tertiary_container = rgba(623b4bff)

$tertiary_fixed = rgba(ffd9e5ff)

$tertiary_fixed_dim = rgba(eeb8cbff)

