alias re='echo "󱗘 Reloading Zsh Profile..." && source $HOME/.config/zsh/.zshrc && echo -e "\033[32m󰄬 Done!\033[0m"'
alias hf='history | fzf | wl-copy'
alias sr='sudo sing-box run -c'

alias ls='lsd -l'
alias la='lsd -la'
alias history='history 1'
alias update='paru -Syu'
alias install='paru -S'
alias remove='paru -Rns'
alias search='paru -Ss'
alias about='paru -Si'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
