# 配色
include colors.conf

# 透明度
background_opacity 0.80
background_blur 1

# 窗口样式
window_padding_width 0 8
hide_window_decorations yes
confirm_os_window_close 0
remember_window_size  no

# 字体设置
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto 
font_size 12
disable_ligatures never

# 光标交互
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
cursor_shape block
shell_integration no-cursor

# 性能优化
repaint_delay 8
input_delay 3
sync_to_monitor yes

# 远程控制
allow_remote_control yes
